apiVersion: v1
kind: ResourceQuota
metadata:
  name: task-manager-resource-quota
  namespace : __NAMESPACE__
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "10"
    services: "5"
